version: 2.1
orbs:
  node: circleci/node@4.1
  slack: circleci/slack@3.4.2

jobs:
  deploy-to-test-site:
    docker:
      - image: rishabhpoddar/supertokens_docs_building # add a new image here for blog
    steps:
      - checkout
      - node/install-packages:
          app-dir: '~/project'
      - run: cd ../ && git clone git@github.com:supertokens/supertokens-backend-website.git
      - run: cd blog && ./buildBlog -g
      - run: git config --global user.email "$EMAIL"
      - run: git config --global user.name "$NAME"
      - run: cd ../supertokens-backend-website && git add --all && git commit -m "blog build" && git push && ./releaseDev.sh
      - slack/status

workflows:
  version: 2
  test:
    jobs:
      - deploy-to-test-site:
          context:
            - slack-notification
          filters:
            branches:
              only:
                - master